{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from assignment_2_final import *\n",
    "import plotly.express as px\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "pd.set_option('display.width', None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Training Item Classification Model...\n",
      "Epoch 1/5\n",
      "\u001b[1m  74/1200\u001b[0m \u001b[32m━\u001b[0m\u001b[37m━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[1m52s\u001b[0m 47ms/step - accuracy: 0.4928 - loss: 1.2889"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-02 18:18:28.892176: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [3,3,64,128] vs. [0]\n",
      "\t [[{{function_node __inference_one_step_on_data_2700}}{{node adam/Mul_19}}]]\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node adam/Mul_19 defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n\n  File \"/var/folders/r9/lmtf195n4jj9qjmbr834vmrm0000gn/T/ipykernel_10931/2856366194.py\", line 3, in <module>\n\n  File \"/Users/leon/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py\", line 1351, in run_task6\n\n  File \"/Users/leon/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py\", line 1177, in train_single_task_models\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 113, in one_step_on_data\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 80, in train_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 383, in apply_gradients\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 448, in apply\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 511, in _backend_apply_gradients\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 120, in _backend_update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 134, in _distributed_tf_update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 131, in apply_grad_to_update_var\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/adam.py\", line 148, in update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/ops/numpy.py\", line 6016, in multiply\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/sparse.py\", line 627, in sparse_wrapper\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/numpy.py\", line 523, in multiply\n\nIncompatible shapes: [3,3,64,128] vs. [0]\n\t [[{{node adam/Mul_19}}]] [Op:__inference_multi_step_on_iterator_2801]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m lambda_values \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m0.0\u001b[39m, \u001b[38;5;241m0.25\u001b[39m, \u001b[38;5;241m0.5\u001b[39m, \u001b[38;5;241m0.75\u001b[39m, \u001b[38;5;241m1.0\u001b[39m]\n\u001b[0;32m----> 3\u001b[0m \u001b[43mrun_task6\u001b[49m\u001b[43m(\u001b[49m\u001b[43mlambda_values\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py:1351\u001b[0m, in \u001b[0;36mrun_task6\u001b[0;34m(lambda_values, epochs, batch_size)\u001b[0m\n\u001b[1;32m   1347\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mrun_task6\u001b[39m(lambda_values, epochs, batch_size\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m50\u001b[39m):\n\u001b[1;32m   1349\u001b[0m     train_X, train_y_1, train_y_2, test_X, test_y_1, test_y_2 \u001b[38;5;241m=\u001b[39m load_fashion_mnist_data()\n\u001b[0;32m-> 1351\u001b[0m     single_results \u001b[38;5;241m=\u001b[39m \u001b[43mtrain_single_task_models\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1352\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtrain_X\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_y_1\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_y_2\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m   1353\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtest_X\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_y_1\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_y_2\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m   1354\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m   1355\u001b[0m \u001b[43m        \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mepochs\u001b[49m\n\u001b[1;32m   1356\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1358\u001b[0m     mtl_results \u001b[38;5;241m=\u001b[39m train_multitask_models(\n\u001b[1;32m   1359\u001b[0m         train_X, train_y_1, train_y_2, \n\u001b[1;32m   1360\u001b[0m         test_X, test_y_1, test_y_2,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1363\u001b[0m         epochs\u001b[38;5;241m=\u001b[39mepochs\n\u001b[1;32m   1364\u001b[0m     )\n\u001b[1;32m   1366\u001b[0m     analyse_results(single_results, mtl_results, lambda_values)\n",
      "File \u001b[0;32m~/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py:1177\u001b[0m, in \u001b[0;36mtrain_single_task_models\u001b[0;34m(train_X, train_y_1, train_y_2, test_X, test_y_1, test_y_2, batch_size, epochs)\u001b[0m\n\u001b[1;32m   1175\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mTraining Item Classification Model...\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1176\u001b[0m start_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[0;32m-> 1177\u001b[0m history_task1 \u001b[38;5;241m=\u001b[39m \u001b[43mmodel_task1\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_X\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_y_1\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mepochs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mtest_X\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_y_1\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1178\u001b[0m task1_train_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime() \u001b[38;5;241m-\u001b[39m start_time\n\u001b[1;32m   1179\u001b[0m task1_test_loss, task1_test_acc \u001b[38;5;241m=\u001b[39m model_task1\u001b[38;5;241m.\u001b[39mevaluate(test_X, test_y_1, verbose\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m)\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node adam/Mul_19 defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n\n  File \"/var/folders/r9/lmtf195n4jj9qjmbr834vmrm0000gn/T/ipykernel_10931/2856366194.py\", line 3, in <module>\n\n  File \"/Users/leon/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py\", line 1351, in run_task6\n\n  File \"/Users/leon/Projects/MSc-AI/Module 9 - Foundations of Machine Learning/Assignment 2/assignment_2_final.py\", line 1177, in train_single_task_models\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 113, in one_step_on_data\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 80, in train_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 383, in apply_gradients\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 448, in apply\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py\", line 511, in _backend_apply_gradients\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 120, in _backend_update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 134, in _distributed_tf_update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 131, in apply_grad_to_update_var\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/optimizers/adam.py\", line 148, in update_step\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/ops/numpy.py\", line 6016, in multiply\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/sparse.py\", line 627, in sparse_wrapper\n\n  File \"/Users/leon/Library/Caches/pypoetry/virtualenvs/msc-ai-yPHgmFUp-py3.12/lib/python3.12/site-packages/keras/src/backend/tensorflow/numpy.py\", line 523, in multiply\n\nIncompatible shapes: [3,3,64,128] vs. [0]\n\t [[{{node adam/Mul_19}}]] [Op:__inference_multi_step_on_iterator_2801]"
     ]
    }
   ],
   "source": [
    "lambda_values = [0.0, 0.25, 0.5, 0.75, 1.0]\n",
    "\n",
    "run_task6(lambda_values, epochs=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "msc-ai-yPHgmFUp-py3.12",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
